# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-23 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_categoryvisitcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryvisitcount',
            old_name='data',
            new_name='date',
        ),
    ]
